---
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Codebuild..
      - |
          # Set and echo environment variable
          ENVIRONMENT_NAME="${ENVIRONMENT}"
          echo "ENVIRONMENT_NAME is set to: $ENVIRONMENT_NAME"
