---
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Codebuild..
      - |
          # Set and echo environment variable
          ENVIRONMENT_NAME="${ENVIRONMENT}"
          echo "ENVIRONMENT_NAME is set to: $ENVIRONMENT_NAME"

          # modify URL based on the environment
          # Use if-else to set the NEW_RELATED_URL
          if [ "$ENVIRONMENT_NAME" = "dev" ]; then
              NEW_RELATED_URL="https://staging.kaloscloud.io/"
          else
              NEW_RELATED_URL="https://kaloscloud.io/"
          fi

          # echo the new URL
          echo "NEW_RELATED_URL is set to: $NEW_RELATED_URL"

          # Update metadata files
          METADATA_FILES=$(find custom_checks -name "*.metadata.json")
          for file in $METADATA_FILES; do
            jq --arg base_url "$BASE_URL" '
              .RelatedUrl |= sub("https://[^/]+"; $base_url) |
              .Remediation.Recommendation.Url |= sub("https://[^/]+"; $base_url)
            ' "$file" > temp.json && mv temp.json "$file"
            
            # Print the updated content
            cat "$file"
            echo "---"
          done


